### PR TITLE
Found an error in the code - changed the formatting.

### PR DESCRIPTION
**Pull request by smikolai**

### CODE REVIEW

**Comment by smikolai** [comment]
@haridsv Please check this quickly, somehow the file that got merged had a formatting error.

**Comment by hdara-sfdc** [comment]
Yes, I see this error:

```
  File "examples/csv2argus.py", line 165
    for metricName in metricNames:
                                 ^
IndentationError: unindent does not match any outer indentation level
```

Looks like the issue existed even at the source, see: https://github.com/salesforce/python-argusclient/pull/7/commits/2a8a3a2efa95b8a86860e19aaba5371c6c700668#diff-a6959f3b5af1b9e9d182753af92b9300R165

Do you want to fix it and send another PR?

**Comment by smikolai** [comment]
I did submit the PR.

On Tue, May 2, 2017 at 11:08 AM, Hari Krishna Dara <notifications@github.com

**Comment by hdara-sfdc** [comment]
OK, I got confused because I was seeing all the old history again. Did you do a pull before making your change? I am just wondering if you base is setup correctly.

**Comment by smikolai** [comment]
Yes.

On Tue, May 2, 2017 at 11:43 AM, Hari Krishna Dara <notifications@github.com

**Comment by hdara-sfdc** [comment]
@smikolai Sorry about dropping the ball on this, but could you look at the issue that I mentioned earlier that this PR is showing old history also, not just your fix? Please also look at the comment from salesforce-cla-v1 and the warning on your last commit.

Once you meet the CLA guidelines, Could you please open a fresh PR that just pushes your fix? Alternatively, send me the diff and I will apply it separately.

**Comment by hdara-sfdc** [comment]
@smikolai Support for the new auth is already there, see this change: https://github.com/salesforce/python-argusclient/commit/f05d628410277b5825b893bf74ef7eba7a3a63eb

Please take a look at the new feature and let me know if you are missing something.

BTW, you are not generating PRs correctly and that is the reason I couldn't merge your previous fix to syntax error till now, and now your new changes are sent to the same PR. Could you find some documentation to understand the right workflow for PRs? I did a quick search and found this:

https://gist.github.com/Chaser324/ce0505fbed06b947d962 

I will close this PR so that you can send a fresh one to include just your fix for syntax error. If you also want to send additional changes to the new auth code, please feel free to send a separate PR.

**Comment by smikolai** [comment]
@hdara-sfdc I looked over the changes - is there no intention for continued support of basic auth as well as the new v2 auth?  My changes suited both.

**Comment by hdara-sfdc** [comment]
@smikolai My understanding is that session-based auth is going away, which implied that the prior endpoint is going away:

https://github.com/salesforce/Argus/wiki/Token-Based-Authentication

But on a second thought, maybe we need to check with Argus devs to confirm if the old endpoint will be left as an option for the service implementation to choose. I will follow up on this.

**Comment by hdara-sfdc** [comment]
On the other hand, look at the code changes done to Java ArgusSDK, it gives the impression that the old endpoint is not going to be supported at all:
 
https://github.com/salesforce/Argus/commit/8e3bbd34d55cedb99559116b59c7e1c155e18f9f#diff-363dcc19c4bedd0bea513e97eb0bc13c

**Comment by hdara-sfdc** [comment]
I confirmed with @bsura that only V2 auth would need to be supported.

**Comment by smikolai** [comment]
Cool, thanks for the confirmation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
